"""
Ground-truth facts for the synthetic ClaimAssist corpus.

These are authored directly, not generated by an LLM, so that the golden
question/answer set (see golden_set.py) has a verifiable source of truth.
LLMs are only used downstream to turn these facts into realistic document
prose (see generate_docs.py) - never to invent the facts themselves.
"""

POLICIES = [
    # --- Homeowners ---
    {
        "policy_number": "HO-88213-4",
        "policy_type": "homeowners",
        "policyholder_name": "Maria Gutierrez",
        "property_address": "214 Birchwood Lane, Springfield",
        "effective_date": "2025-09-01",
        "expiration_date": "2026-09-01",
        "dwelling_limit_usd": 350_000,
        "personal_property_limit_usd": 175_000,
        "deductibles": {
            "standard": 1_000,
            "wind_hail": 2_500,
        },
        "riders": [],
        "exclusions": [
            "Flood damage",
            "Earth movement (including earthquake and land subsidence)",
            "Wear, tear, and gradual deterioration",
            "Mold, except when directly resulting from a covered water damage event",
            "Intentional acts by the insured",
        ],
    },
    {
        "policy_number": "HO-4471-9",
        "policy_type": "homeowners",
        "policyholder_name": "David Chen",
        "property_address": "88 Maple Court, Riverside",
        "effective_date": "2025-11-15",
        "expiration_date": "2026-11-15",
        "dwelling_limit_usd": 500_000,
        "personal_property_limit_usd": 250_000,
        "deductibles": {
            "standard": 1_500,
            "wind_hail": 5_000,
        },
        "riders": ["Scheduled jewelry rider: $15,000 limit"],
        "exclusions": [
            "Flood damage",
            "Earth movement (including earthquake and land subsidence)",
            "Wear, tear, and gradual deterioration",
            "Mold, except when directly resulting from a covered water damage event",
            "War and nuclear hazard",
            "Intentional acts by the insured",
        ],
    },
    {
        "policy_number": "HO-1120-7",
        "policy_type": "homeowners",
        "policyholder_name": "Angela Torres",
        "property_address": "5 Meadowbrook Drive, Lakeside",
        "effective_date": "2026-01-10",
        "expiration_date": "2027-01-10",
        "dwelling_limit_usd": 275_000,
        "personal_property_limit_usd": 137_500,
        "deductibles": {
            "standard": 500,
            "wind_hail": 1_000,
        },
        "riders": [],
        "exclusions": [
            "Flood damage",
            "Earth movement (including earthquake and land subsidence)",
            "Wear, tear, and gradual deterioration",
            "Mold, except when directly resulting from a covered water damage event",
            "Intentional acts by the insured",
        ],
    },
    # --- Auto ---
    {
        "policy_number": "AU-3387-1",
        "policy_type": "auto",
        "policyholder_name": "James Whitfield",
        "vehicle": "2019 Honda Accord",
        "effective_date": "2025-08-01",
        "expiration_date": "2026-08-01",
        "liability_limits": "$100,000/$300,000",
        "uninsured_motorist_limits": "$100,000/$300,000",
        "deductibles": {
            "collision": 500,
            "comprehensive": 250,
        },
        "riders": [],
        "exclusions": [
            "Racing or speed contests",
            "Commercial use of the vehicle",
            "Intentional damage",
            "Use of the vehicle to commit a crime",
        ],
    },
    {
        "policy_number": "AU-7742-5",
        "policy_type": "auto",
        "policyholder_name": "Priya Nair",
        "vehicle": "2021 Toyota RAV4",
        "effective_date": "2025-12-01",
        "expiration_date": "2026-12-01",
        "liability_limits": "$250,000/$500,000",
        "uninsured_motorist_limits": "$250,000/$500,000",
        "deductibles": {
            "collision": 1_000,
            "comprehensive": 500,
        },
        "riders": ["Rental reimbursement: $30/day, maximum 30 days"],
        "exclusions": [
            "Racing or speed contests",
            "Commercial use of the vehicle",
            "Intentional damage",
            "Use of the vehicle to commit a crime",
        ],
    },
    {
        "policy_number": "AU-2298-3",
        "policy_type": "auto",
        "policyholder_name": "Marcus Webb",
        "vehicle": "2017 Ford F-150",
        "effective_date": "2026-02-20",
        "expiration_date": "2027-02-20",
        "liability_limits": "$50,000/$100,000",
        "uninsured_motorist_limits": "$50,000/$100,000",
        "deductibles": {
            "collision": 1_000,
            "comprehensive": 1_000,
        },
        "riders": [],
        "exclusions": [
            "Racing or speed contests",
            "Commercial use of the vehicle",
            "Livery or ride-share use",
            "Intentional damage",
        ],
    },
    # --- Health ---
    {
        "policy_number": "HI-5502-8",
        "policy_type": "health",
        "policyholder_name": "Sofia Ramirez",
        "plan_type": "Individual",
        "effective_date": "2026-01-01",
        "expiration_date": "2026-12-31",
        "deductible_usd": 2_000,
        "out_of_pocket_max_usd": 6_500,
        "coinsurance_after_deductible": "20%",
        "copays": {
            "primary_care": 30,
            "specialist": 60,
            "emergency_room": 350,
        },
        "riders": [],
        "exclusions": [
            "Cosmetic procedures",
            "Experimental or investigational treatment",
            "Injuries sustained during illegal activity",
        ],
    },
    {
        "policy_number": "HI-6614-2",
        "policy_type": "health",
        "policyholder_name": "The Okafor Family",
        "plan_type": "Family",
        "effective_date": "2026-03-01",
        "expiration_date": "2027-02-28",
        "deductible_usd": 4_000,
        "embedded_individual_deductible_usd": 2_000,
        "out_of_pocket_max_usd": 12_000,
        "coinsurance_after_deductible": "20%",
        "copays": {
            "primary_care": 25,
            "specialist": 50,
            "emergency_room": 300,
        },
        "riders": [],
        "exclusions": [
            "Cosmetic procedures",
            "Experimental or investigational treatment",
            "Injuries sustained during illegal activity",
        ],
    },
    {
        "policy_number": "HI-3309-6",
        "policy_type": "health",
        "policyholder_name": "Robert Kim",
        "plan_type": "Individual High-Deductible (HSA-eligible)",
        "effective_date": "2025-10-01",
        "expiration_date": "2026-09-30",
        "deductible_usd": 3_500,
        "out_of_pocket_max_usd": 7_000,
        "coinsurance_after_deductible": "10%",
        "copays": {
            "primary_care": "Applied to deductible, no fixed copay",
            "specialist": "Applied to deductible, no fixed copay",
            "emergency_room": "Applied to deductible, no fixed copay",
        },
        "riders": [],
        "exclusions": [
            "Cosmetic procedures",
            "Experimental or investigational treatment",
            "Injuries sustained during illegal activity",
        ],
    },
]

CLAIMS = [
    {
        "claim_id": "CLM-2026-0301",
        "policy_number": "HO-88213-4",
        "date_of_loss": "2026-03-03",
        "loss_type": "wind_hail",
        "injury": False,
        "facts": (
            "Severe wind and hail storm, gusts up to 65 mph. Missing roof "
            "shingles on south-facing slope, cracked skylight, water-stained "
            "ceiling below skylight, downed east-side fence panel, oak branch "
            "dented detached garage roof (no penetration). No injuries. "
            "Neighbor John Alvarez corroborated storm timing and fence damage. "
            "Roof repair/skylight estimate $8,450. Fence repair estimate $1,200. "
            "Total estimated repair cost $9,650. Wind/hail deductible applies."
        ),
    },
    {
        "claim_id": "CLM-2026-0412",
        "policy_number": "AU-3387-1",
        "date_of_loss": "2026-04-12",
        "loss_type": "collision",
        "injury": True,
        "facts": (
            "Rear-ended another vehicle stopped at a red light on Route 9. "
            "James Whitfield's 2019 Honda Accord sustained front-end damage: "
            "cracked bumper, bent hood, damaged radiator support. Repair "
            "estimate $6,200. Collision deductible applies. James reported "
            "neck pain/stiffness after the impact and was seen at an urgent "
            "care clinic the same day (see medical note MED-0412-A)."
        ),
    },
    {
        "claim_id": "CLM-2026-0520",
        "policy_number": "HI-5502-8",
        "date_of_loss": "2026-05-20",
        "loss_type": "injury",
        "injury": True,
        "facts": (
            "Sofia Ramirez fell at home and injured her right wrist. Went to "
            "the emergency room the same day; X-ray showed a distal radius "
            "fracture, closed reduction performed, cast applied, discharged "
            "with an orthopedic referral (see medical note MED-0520-A). "
            "ER visit billed $4,800. Emergency room copay and deductible "
            "apply per plan terms."
        ),
    },
    {
        "claim_id": "CLM-2026-0214",
        "policy_number": "HO-1120-7",
        "date_of_loss": "2026-02-14",
        "loss_type": "water_damage",
        "injury": False,
        "facts": (
            "Burst supply line pipe in the upstairs bathroom of Angela "
            "Torres's home caused water damage to the bathroom ceiling and "
            "downstairs living room flooring. Plumber confirmed sudden pipe "
            "failure, not gradual leakage. Repair estimate $6,300. Standard "
            "deductible applies (not a wind/hail event). No injuries."
        ),
    },
    {
        "claim_id": "CLM-2026-0601",
        "policy_number": "AU-7742-5",
        "date_of_loss": "2026-06-01",
        "loss_type": "comprehensive",
        "injury": False,
        "facts": (
            "Priya Nair's 2021 Toyota RAV4 windshield was cracked by road "
            "debris on the highway; minor hail dents on the hood were also "
            "noted at inspection. Repair estimate $2,100. Comprehensive "
            "deductible applies. Vehicle was in the shop for 3 days; rental "
            "reimbursement claimed at $30/day ($90 total), within policy "
            "rider limits. No injuries."
        ),
    },
]

MEDICAL_NOTES = [
    {
        "note_id": "MED-0412-A",
        "claim_id": "CLM-2026-0412",
        "patient_name": "James Whitfield",
        "visit_date": "2026-04-12",
        "facility_type": "Urgent care clinic",
        "facts": (
            "Chief complaint: neck pain and stiffness following a motor "
            "vehicle accident earlier the same day. Assessment: cervical "
            "strain (whiplash). Cervical spine X-ray performed, no fracture. "
            "Treatment: ibuprofen, soft cervical collar recommended, "
            "follow-up in 2 weeks if symptoms persist. Visit billed $450."
        ),
    },
    {
        "note_id": "MED-0520-A",
        "claim_id": "CLM-2026-0520",
        "patient_name": "Sofia Ramirez",
        "visit_date": "2026-05-20",
        "facility_type": "Emergency room",
        "facts": (
            "Chief complaint: fall at home, right wrist pain and swelling. "
            "X-ray revealed a distal radius fracture. Closed reduction "
            "performed under procedural sedation, cast applied. Discharged "
            "same day with an orthopedic follow-up referral. Visit billed "
            "$4,800."
        ),
    },
    {
        "note_id": "MED-0603-A",
        "claim_id": "CLM-2026-0520",
        "patient_name": "Sofia Ramirez",
        "visit_date": "2026-06-03",
        "facility_type": "Orthopedic follow-up",
        "facts": (
            "Follow-up for distal radius fracture. Cast intact, follow-up "
            "X-ray shows healing on track. Plan: continue cast 3 more weeks, "
            "physical therapy referral to begin after cast removal. Visit "
            "billed $320."
        ),
    },
]


def get_policy(policy_number: str) -> dict:
    return next(p for p in POLICIES if p["policy_number"] == policy_number)


def get_claims_for_policy(policy_number: str) -> list[dict]:
    return [c for c in CLAIMS if c["policy_number"] == policy_number]


def get_notes_for_claim(claim_id: str) -> list[dict]:
    return [n for n in MEDICAL_NOTES if n["claim_id"] == claim_id]
